dir: internal/mocks/{{.SrcPackageName}}
filename: "mock_{{.InterfaceName}}.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/tombenke/go-application-template/internal/application:
    interfaces:
      AppService: {}
